### ISSUE TITLE
Request for GPU Support in Calculation Code

### ISSUE THREAD

**Issue by BaekAyoung** [ci-lab-cz/streamd#26]
Hi,

First of all, thank you for sharing this great project. I have been using the code for my calculations and it works well. However, I'm interested in running these calculations on a GPU rather than a CPU.

Could you please let me know if there is a version of the code that supports GPU computations, or if there are any modifications I need to make to enable GPU support?

Thanks in advance for your help!

Best, 
Ayoung Baek

**Comment by DrrDom** [comment]
Hi Ayoung,
GPU can be applied to pkasolver protonation and for docking with gnina. Regarding the former, GPU does not give much advances and may be even slower than CPU. @Feriolet, experimented a lot with that and may provide more details. Regarding the docking part, this is not linked to easydock at all. You install and setup gnina completely independently.

**Comment by BaekAyoung** [comment]
Hi @DrrDom,

Thank you for the information. I understand that GPU can be used for pkasolver protonation and docking with gnina.

However, my main interest is in using GPU for the equilibration and MD steps to speed up the calculations. Could you please provide the commands or modifications needed to enable GPU support for these steps?

Thank you again for your assistance!

Best regards,
Ayoung Baek

**Comment by DrrDom** [comment]
Sorry for that, I wrongly recognized your question as in easydock repository))
@avnikonenko, will provide more details about that.

**Comment by avnikonenko** [comment]
Hello!
Thank you for the interest in this project! 
It shouldn't create much issues to implement GPU calculations support, approximately by the end of this or next week it should be done. I am starting working on this.

**Comment by avnikonenko** [comment]
Hello!
@BaekAyoung ,
GPU support is now has been implemented and I hope you will enjoy using the new feature!
All possibilities are described in the README "GPU usage" section.
I ran multiple tests, checking also gpu usage and it works smoothly.
Let me know if you have any further questions or will find any problem!
