### ISSUE TITLE
unrecognixed arguments: --device gpu –gpu_ids 0

### ISSUE THREAD

**Issue by jisunchoii** [ci-lab-cz/streamd#28]
I created a virtual environment utilizing env_gpu.yml and the device option does not appear.
There seems to be only one version of this repo, how do I fix it?

Running this:
`run_md -p protein.pdb -l ligands.sdf --md_time 1 --device gpu --gpu_ids 0 1 2 3`

Gives me an error: 
`run_md: error: unrecognized arguments: --device gpu --gpu_ids 0 1 2 3`

**Comment by avnikonenko** [comment]
Have you installed the package by pip install git+https://github.com/ci-lab-cz/streamd.git ? if not try to uninstall the pip version and install it from the github

**Comment by jisunchoii** [comment]
thanks issue resolved!
