### ISSUE TITLE
Assistance Required with solv_ions.sh Script in streaMD

### ISSUE THREAD

**Issue by BaekAyoung** [ci-lab-cz/streamd#29]
Hi, 

I am using the streaMD for MD simulations and am currently trying to reduce the calculation time by modifying the box size and box type **in the solv_ions.sh script.** Specifically, I am adjusting the parameters for the box shape to dodecahedron and the distance using gmx editconf, as shown in the script below:

```
gmx editconf -f complex.gro -o newbox.gro -bt dodecahedron -d 0.8
gmx solvate -cp newbox.gro -cs spc216.gro -p topol.top -o solv.gro
```

However, I have noticed that the changes I make to the box size and type are not being applied properly, and the simulation proceeds without reflecting these adjustments. 

Could you please advise why the changes to the box size and type are not taking effect, or how I can ensure these parameters are properly applied?

I would greatly appreciate your insights.

Best regards,
Ayoung Baek

**Comment by avnikonenko** [comment]
Hello!
How exactly did you change the parameters? Do you run every time a new run and make sure current working dir does not exist so no checkpoints files can be find and reused?

**Comment by BaekAyoung** [comment]
Hi, 
I attempted to modify the box size and type in the solv_ions.sh file located in the streamd/scripts/script_sh path and then performed the calculation.

```
#!/bin/bash
# wdir
#Solvate

>&2 echo 'Script running:***************************** Solvation step *********************************'
cd $wdir
gmx editconf -f complex.gro -o newbox.gro -bt dodecahedron -d 0.8 #Warning about bad box - wrong number of atoms (https://gromacs.org-gmx-users.maillist.sys.kth.narkive.com/q4NXMAoY/bad-box-error) Lena version
gmx solvate -cp newbox.gro -cs spc216.gro -p topol.top -o solv.gro || { echo "Failed to run command  at line ${LINENO} of ${BASH_SOURCE}" && exit 1; }

#Add ions
>&2 echo 'Script running:***************************** Ions *********************************'
#use grompp to assemble *tpr file () using any *mdp file
gmx grompp -f ions.mdp -c solv.gro -p topol.top -o ions.tpr   || { echo "Failed to run command  at line ${LINENO} of ${BASH_SOURCE}" && exit 1; }
#-maxwarn 10
#FATAL error SDMSO type not found -> try renaming to SDmso
```

gmx genion -s ions.tpr -o solv_ions.gro -p topol.top -pname NA -nname CL -neutral <<< SOL  || { echo "Failed to run command  at line ${LINENO} of ${BASH_SOURCE}" && exit 1; }
However, when I check the log file, the box size and type are not changed, as seen in the following:

```
Script running:***************************** Solvation step *********************************
Command line:
  gmx editconf -f complex.gro -o newbox.gro -c -d 1.0 -bt cubic
```
  
Could you advise how I can ensure that the simulation runs freshly each time and that no checkpoint files are found or reused when the current working directory exists?
